{% set name = "databricks-sql-connector" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4302828afa17b9f993dc63143aa35c76e30d2b46bdb4bcc47452d4c44bb412d8
  patches:
    - 0001_relax_constraints.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8.0,<4.0.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8.0,<4.0.0
    - thrift >=0.16.0,<0.21.0
    - pandas >=1.2.5
    - pyarrow >=14.0.1
    - lz4 >=4.0.2,<5.0.0
    - requests >=2.18.1,<3.0.0
    - oauthlib >=3.1.0,<4.0.0
    # more restrictive python 3.11 requirement for noarch
    - numpy >=1.23.4
    - openpyxl >=3.0.10
    - urllib3 >=1.26
  run_constrained:
    - sqlalchemy >=2.0.21
    - alembic >=1.0.11,<2.0.0

test:
  imports:
    - databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html
  dev_url: https://github.com/databricks/databricks-sql-python

extra:
  recipe-maintainers:
    - xylar
